output_path: "./output_${SLURM_JOB_ID}_${NOW}"
dataset_file: datasets.galaxies

multigpu: no
mp_loaders: 4
batch_size: 4
learning_rate: 1.0e-4
max_epochs: 3000
scheduler_lambda: 0.998
beta_schedule: "cosine" # One of ["cosine", "linear"]
polyak_alpha: 0.99
preprocessing: 'scale' # ['none', 'scale']
backbone: 'spectrumunet' # ['spectrumunet']

use_logger: no
conditioning: x-attention
time_steps: 250

spectrumunet:
    dim: 64
    attention_depths: [3, 4]
    dim_mults: [1, 2, 4, 8, 16]

load_from: null

load_con_from: null
latent_dimensionality: 128
con_backbone: 'resnet'

resnet:
  base_channels: 64
  channel_mults: [1, 2, 4, 8, 16]

num_eval_predictions: 25
num_eval_samples: 50
num_shown: 5
num_con_mean: 5